title: "Raj Mehta | Cybersecurity Knowledge Hub"
description: "Clear, practical guides on vulnerability management, DevSecOps, and cloud security."
url: "https://rmehta-vm.github.io"

remote_theme: mmistakes/minimal-mistakes@4.24.0

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-include-cache

collections:
  kb:
    output: true
    permalink: /kb/:path/
    sort_by: order
    order: ascending

# Site-wide defaults for KB pages
defaults:
  - scope:
      path: ""
      type: kb
    values:
      layout: single
      author_profile: false
      toc: true
      show_date: false
      read_time: false
      share: false
      related: false
      sidebar: false 

head_scripts:
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js

include:
  - _pages
  - _kb
  - assets

markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
