title: "Vulnerability Management KnowledgeBase"
description: "Clear, practical guides on vulnerability management, DevSecOps, and cloud security."
url: "https://rmehta-vm.github.io"

remote_theme: mmistakes/minimal-mistakes@4.24.0

plugins:
  - jekyll-sitemap
  - jekyll-include-cache

collections:
  kb:
    output: true
    permalink: /kb/:path/

defaults:
  - scope:
      path: ""
      type: kb
    values:
      layout: single
      author_profile: false
      toc: true
      classes: wide
      show_date: false
      read_time: false
      share: false          
      related: false        
      sidebar:
        nav: "kb"

head_custom: true

markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
